print('hello,all the beautiful people in the universe')
print("the end or is it? keep watching to learn more about python 3")
print("My hovercraft is full of eels")
print(7*6)
Greeting = "Namaste"
Name = input("Enter your name:")
print(Greeting + ' ' + Name)
print("")
splitscreen =("This string\nhas been\nsplit over\nmultiple times")
print(splitscreen)
