print('hello,all the beautiful people in the universe')
print("the end or is it? keep watching to learn more about python 3")
print("My hovercraft is full of eels")
print(7*6)
Greeting = "Namaste"
Name = input("Enter your name:")
print(Greeting + ' ' + Name)
print("")
splitscreen =("This string\nhas been\nsplit over\nmultiple times")
print(splitscreen)
print("")
insertion =("There\thave\tbeen\tmany\tinsertions")
print(insertion)
print("")
print("")
Line1 =("S.No.\t\tName\t\t\tType")
print(Line1)
Line2 =("1.\t\tPikachu\t\t\tElectric")
print(Line2)
Line3 =("2.\t\tCharizard\t\tFire")
print(Line3)
Line4 =("2.\t\tBlastoise\t\tWater")
print(Line4)
Line5 =("3.\t\tVenasaur\t\tGrass")
print(Line5)
Line6 =("4\t\tDarkrai\t\t\tDark")
print(Line6)
print()
Table =("Number 1\tThe Larch\nNumber 2\tThe Horse Chestnut")
print(Table)
